ercheck/config/routes.rb
Ercheck::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'info#home'

  resources :functions

  resources :departments

  resources :designations

  resources :highest_qualifications

  resources :enquiries

  resources :employements

  resources :universities

  resources :employers

  resources :statuses

  resources :employees

  resources :datafiles

  get "info/home"

  get "info/faq"

  get "info/support"

  get "info/contact"

  get "info/terms"

  get "info/about"

  get "info/search"

  get "info/privacy"

  get "info/advertise"

  get "info/help"

  get "info/career"

  get "info/associate"

  get "info/access_error"

  resources :employee_imports
  resources :employees do
    collection { post :import }
  end

  devise_for :users do
        get '/users/sign_out' => 'devise/sessions#destroy'
  end

  match "admin/users/:id/change_managers" => "admin/users#change_managers"

end

ercheck/app/models/university.rb
class University < ActiveRecord::Base

  include CsvMapper

  has_many :employees

  attr_accessible :address, :name


=begin
  def self.fetchcsv(input_csv) #'C:\\DATA\\univ.csv'
    include CsvMapper

    results = CsvMapper.import(input_csv) do
      map_to University
      # Map to the University  ActiveRecord class (defined above) instead of the default OpenStruct.

      after_row lambda{|row, university| university.save }  # Call this lambda and save each record after it's parsed.

      start_at_row 1
      [name, address]

    end
  end
=end
end

ercheck/app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController

  load_and_authorize_resource

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @universities }
    end
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
    @university = University.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @university }
    end
  end

  # GET /universities/new
  # GET /universities/new.json
  def new
    @university = University.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @university }
    end
  end

  # GET /universities/1/edit
  def edit
    @university = University.find(params[:id])
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(params[:university])

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render json: @university, status: :created, location: @university }
      else
        format.html { render action: "new" }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /universities/1
  # PUT /universities/1.json
  def update
    @university = University.find(params[:id])

    respond_to do |format|
      if @university.update_attributes(params[:university])
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university = University.find(params[:id])
    @university.destroy

    respond_to do |format|
      format.html { redirect_to universities_url }
      format.json { head :no_content }
    end
  end
end

ercheck/app/helpers/universities_helper.rb
module UniversitiesHelper
end

ercheck/app/views/universities/_form.html.erb
<%= form_for(@university) do |f| %>
  <% if @university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% @university.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ercheck/app/views/universities/edit.html.erb
<h1>Editing university</h1>

<%= render 'form' %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

ercheck/app/views/universities/index.html.erb
<h1>Listing universities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @universities.each do |university| %>
  <tr>
    <td><%= university.name %></td>
    <td><%= university.address %></td>
    <td><%= link_to 'Show', university %></td>
    <td><%= link_to 'Edit', edit_university_path(university) %></td>
    <td><%= link_to 'Destroy', university, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New University', new_university_path %>

ercheck/app/views/universities/new.html.erb
<h1>New university</h1>

<%= render 'form' %>

<%= link_to 'Back', universities_path %>

ercheck/app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @university.name %>
</p>

<p>
  <b>Address:</b>
  <%= @university.address %>
</p>


<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>