ercheck/config/routes.rb
Ercheck::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'info#home'

  resources :functions

  resources :departments

  resources :designations

  resources :highest_qualifications

  resources :enquiries

  resources :employements

  resources :universities

  resources :employers

  resources :statuses

  resources :employees

  resources :datafiles

  get "info/home"

  get "info/faq"

  get "info/support"

  get "info/contact"

  get "info/terms"

  get "info/about"

  get "info/search"

  get "info/privacy"

  get "info/advertise"

  get "info/help"

  get "info/career"

  get "info/associate"

  get "info/access_error"

  resources :employee_imports
  resources :employees do
    collection { post :import }
  end

  devise_for :users do
        get '/users/sign_out' => 'devise/sessions#destroy'
  end

  match "admin/users/:id/change_managers" => "admin/users#change_managers"

end

ercheck/app/models/designation.rb
class Designation < ActiveRecord::Base
  attr_accessible :description, :name
end

ercheck/app/controllers/designations_controller.rb
class DesignationsController < InheritedResources::Base
end

ercheck/app/helpers/designations_helper.rb
module DesignationsHelper
end

ercheck/app/views/designations/_form.html.erb
<%= form_for(@designation) do |f| %>
  <% if @designation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@designation.errors.count, "error") %> prohibited this designation from being saved:</h2>

      <ul>
      <% @designation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ercheck/app/views/designations/edit.html.erb
<h1>Editing designation</h1>

<%= render 'form' %>

<%= link_to 'Show', @designation %> |
<%= link_to 'Back', designations_path %>

ercheck/app/views/designations/index.html.erb
<h1>Listing designations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @designations.each do |designation| %>
  <tr>
    <td><%= designation.name %></td>
    <td><%= designation.description %></td>
    <td><%= link_to 'Show', designation %></td>
    <td><%= link_to 'Edit', edit_designation_path(designation) %></td>
    <td><%= link_to 'Destroy', designation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Designation', new_designation_path %>

ercheck/app/views/designations/new.html.erb
<h1>New designation</h1>

<%= render 'form' %>

<%= link_to 'Back', designations_path %>

ercheck/app/views/designations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @designation.name %>
</p>

<p>
  <b>Description:</b>
  <%= @designation.description %>
</p>


<%= link_to 'Edit', edit_designation_path(@designation) %> |
<%= link_to 'Back', designations_path %>