ercheck/config/routes.rb
Ercheck::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'info#home'

  resources :functions

  resources :departments

  resources :designations

  resources :highest_qualifications

  resources :enquiries

  resources :employements

  resources :universities

  resources :employers

  resources :statuses

  resources :employees

  resources :datafiles

  get "info/home"

  get "info/faq"

  get "info/support"

  get "info/contact"

  get "info/terms"

  get "info/about"

  get "info/search"

  get "info/privacy"

  get "info/advertise"

  get "info/help"

  get "info/career"

  get "info/associate"

  get "info/access_error"

  resources :employee_imports
  resources :employees do
    collection { post :import }
  end

  devise_for :users do
        get '/users/sign_out' => 'devise/sessions#destroy'
  end

  match "admin/users/:id/change_managers" => "admin/users#change_managers"

end

ercheck/app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :description, :name
end

ercheck/app/controllers/departments_controller.rb
class DepartmentsController < InheritedResources::Base
end

ercheck/app/helpers/departments_helper.rb
module DepartmentsHelper
end

ercheck/app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ercheck/app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

ercheck/app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departments.each do |department| %>
  <tr>
    <td><%= department.name %></td>
    <td><%= department.description %></td>
    <td><%= link_to 'Show', department %></td>
    <td><%= link_to 'Edit', edit_department_path(department) %></td>
    <td><%= link_to 'Destroy', department, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Department', new_department_path %>

ercheck/app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

ercheck/app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @department.name %>
</p>

<p>
  <b>Description:</b>
  <%= @department.description %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>