ercheck/config/routes.rb
Ercheck::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users

  root :to => 'info#home'

  resources :functions

  resources :departments

  resources :designations

  resources :highest_qualifications

  resources :enquiries

  resources :employements

  resources :universities

  resources :employers

  resources :statuses

  resources :employees

  resources :datafiles

  get "info/home"

  get "info/faq"

  get "info/support"

  get "info/contact"

  get "info/terms"

  get "info/about"

  get "info/search"

  get "info/privacy"

  get "info/advertise"

  get "info/help"

  get "info/career"

  get "info/associate"

  get "info/access_error"

  resources :employee_imports
  resources :employees do
    collection { post :import }
  end

  devise_for :users do
        get '/users/sign_out' => 'devise/sessions#destroy'
  end

  match "admin/users/:id/change_managers" => "admin/users#change_managers"

end

ercheck/app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :employements
  has_many :employees, :through => :employements
  has_many :users
  belongs_to :industry

  attr_accessible :address, :city, :employer_code, :name, :employement_ids
  accepts_nested_attributes_for :employements, :allow_destroy => true


end

ercheck/app/controllers/employers_controller.rb
class EmployersController < ApplicationController

  load_and_authorize_resource

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employers }
    end
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
    @employer = Employer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employer }
    end
  end

  # GET /employers/new
  # GET /employers/new.json
  def new
    @employer = Employer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employer }
    end
  end

  # GET /employers/1/edit
  def edit
    @employer = Employer.find(params[:id])
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(params[:employer])

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render json: @employer, status: :created, location: @employer }
      else
        format.html { render action: "new" }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employers/1
  # PUT /employers/1.json
  def update
    @employer = Employer.find(params[:id])

    respond_to do |format|
      if @employer.update_attributes(params[:employer])
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer = Employer.find(params[:id])
    @employer.destroy

    respond_to do |format|
      format.html { redirect_to employers_url }
      format.json { head :no_content }
    end
  end
end

ercheck/app/helpers/employers_helper.rb
module EmployersHelper
end

ercheck/app/views/employers/_form.html.erb
<%= form_for(@employer) do |f| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% @employer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :employer_code %><br />
    <%= f.text_field :employer_code %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ercheck/app/views/employers/edit.html.erb
<h1>Editing employer</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

ercheck/app/views/employers/index.html.erb
<h1>Listing employers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Employer code</th>
    <th>Address</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employers.each do |employer| %>
  <tr>
    <td><%= employer.name %></td>
    <td><%= employer.employer_code %></td>
    <td><%= employer.address %></td>
    <td><%= employer.city %></td>
    <td><%= link_to 'Show', employer %></td>
    <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
    <td><%= link_to 'Destroy', employer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employer', new_employer_path %>

ercheck/app/views/employers/new.html.erb
<h1>New employer</h1>

<%= render 'form' %>

<%= link_to 'Back', employers_path %>

ercheck/app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employer.name %>
</p>

<p>
  <b>Employer code:</b>
  <%= @employer.employer_code %>
</p>

<p>
  <b>Address:</b>
  <%= @employer.address %>
</p>

<p>
  <b>City:</b>
  <%= @employer.city %>
</p>


<%= link_to 'Edit', edit_employer_path(@employer) %> |
<%= link_to 'Back', employers_path %>